### ISSUE TITLE
Suggestions for readme

### ISSUE THREAD

**Issue by dgudim** [brayo-pip/aw-watcher-lastfm#6]
Another option for installation is

```
cargo install --git https://github.com/brayo-pip/aw-watcher-lastfm.git
```
and then add to aw-qt.toml (autostart_modules), no systemd required and no manual PATH shenanigans

**Comment by 0xbrayo** [comment]
Make the PR I will merge.

**Comment by dgudim** [comment]
done

**Comment by 0xbrayo** [comment]
Thanks
